---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pet
  name: simple-app-deployment
  labels:
    app: simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-http
        image: stefanprodan/podinfo:latest
        ports:
        - containerPort: 9898
        resources:
          requests:
            cpu: 400m
            memory: 128M
          limits:
            cpu: 800m
            memory: 256M
        readinessProbe:
          tcpSocket:
            port: 9898
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9898
          initialDelaySeconds: 15
          periodSeconds: 10


---
#Service

apiVersion: v1
kind: Service
metadata:
  namespace: pet
  name: simple-app-service
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP

---
#Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: pet
  name: simple-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: simple-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-app-service
                port:
                  number: 80
